### ISSUE TITLE
Implement data_retriever service

### ISSUE THREAD

**Issue by h-karim** [h-karim/mtl-bed-bug-reports#1]
Service should be able to:

- [ ]  #2 
- [ ] #3
- [ ] pass the data to core
- [ ] Implement authentication using JWT tokens
- [ ] Expose configs that can be changed through an admin page
